[package]
name = "wright"
version = "0.1.0"
authors = ["Chakrit Wichian <service@chakrit.net>"]
edition = "2018"

[dependencies]
anyhow = "^1.0"
git2 = "^0.13"
tokei = "^12.0"
toml = "^0.5"
zip = "^0.5"
